[workspace]
members = [
  "runner",
  "common",
  "advent-of-code-2022",
  "advent-of-code-2021",
  "advent-of-code-2020",
  "advent-of-code-2019",
  "advent-of-code-2018",
  "advent-of-code-2015",
  "advent-of-code-2016",
]
