[package]
authors.workspace = true
edition.workspace = true
name = "year_2018"
version.workspace = true

[dependencies]
anyhow.workspace = true
common.workspace = true
itertools.workspace = true
log.workspace = true
multimap.workspace = true
multiset.workspace = true
nom.workspace = true
rayon.workspace = true
regex.workspace = true
